spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BankingApp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

bankingapp:
  auth:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  file:
    upload-dir: ./uploaded-files

  mail:
    host: smtp.outlook.com
    port: 587
    username: abginternship1@outlook.com
    password: Marwan2001
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  logging:
    level:
      root: info  # Global log level
      org.springframework: warn  # Log level for Spring framework

